---
title: Indivisible Johnstown
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: Resisting the Dangerous Trump Agenda
email: indivisiblejohnstown@gmail.com
baseurl: 
Key: 
"@IndivisiblJtown": Twitter
Indivisible Johnstown: Facebook
background-image: "/uploads/indivisiblejohnstown_SiteHeader-18ab15.jpg"
member-count: 56
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: |-
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-105306689-1', 'auto');
    ga('send', 'pageview');

  </script>
